### ISSUE TITLE
Direct Ask a Question link to discussions instead of issues

### ISSUE THREAD

**Issue by areynold** [uillinois-community/uillinois-community.github.io#22]
The "Ask a Question" link on the portal index would be a better fit for the Discussions section. Issues could then be reserved for fixes or enhancements to the page itself.

**Comment by jtgorman** [comment]
That makes sense to me, it feels awkward currently to me to have Issues that never close out or could be closed out.

**Comment by jtgorman** [comment]
Two yeas and no nays, I'm approving it ;)
