### ISSUE TITLE
repo in limbo

### ISSUE THREAD

**Issue by jtgorman** [uillinois-community/uillinois-community.github.io#27]
So, I tried transferring a repo from the UIUCLibrary to uillinois-community. I can create repos in both, so I assumed it wouldn't be an issue. However, it seems to have gotten stuck in some sort of limbo. I suspect it's likely that it was a private repo and it came over w/o anyhone "owning" it.

original repo was UIUCLibrary/powershell-scripts.git

**Comment by areynold** [comment]
Yeah, this seems related to the base org permissions issue I mentioned this morning. Any objection to making the powershell-scripts repo public?

**Comment by jtgorman** [comment]
Nope, goal was to share it, so public is fine.
