### ISSUE TITLE
Update our GitHub pages to use a static site generator? 

### ISSUE THREAD

**Issue by edthedev** [uillinois-community/uillinois-community.github.io#31]
I think switching to a GitHub pages solution that allows checking in Markdown would be help this resource grow.

I'm partial to using [11ty ](https://www.11ty.dev/), setup by following [this guide](https://www.linkedin.com/pulse/eleventy-github-pages-lea-tortay/).

In particular, I use this [GitHub pages action](https://github.com/marketplace/actions/github-pages-action) which seems to be very popular.

[Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll) is the default option, but I've had less success with it - maybe because I'm not as good with Ruby Gems as I am with Node Package Manager.

**Comment by areynold** [comment]
No objection from me. I'm not a huge jekyll fan.

There might be a case to be made for keeping the github default for maintenance continuity, but I'm not sure how many ruby devs we have these days. If there's going to be a learning curve anyway, I would rather use a familiar stack.

**Comment by trombonekenny** [comment]
As long as someone's maintaining the static site generator and tools, sure. In my experience on edge projects like this, those things tend to bitrot.

**Comment by edthedev** [comment]
@areynold Sweet.

I've started a draft conversion at https://github.com/uillinois-community/uillinois-community.github.io/tree/11ty

I would appreciate extra eyes on it.

I need to hunt down the key management for the GitHub action, and then I think it will be ready to review.

**Comment by edthedev** [comment]
I think the branch is ready to review now.

**Comment by jtgorman** [comment]
I like the idea of this. Sorry for the late response, was on vacation and then been busy catching up before Thanksgiving. Making a note in my calendar now to look at this next week.
