### ISSUE TITLE
Contrast warnings in WAVE accessibility evaluator

### ISSUE THREAD

**Issue by edthedev** [uillinois-community/uillinois-community.github.io#36]
The [WAVE plugin for Chrome](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related?hl=en) warns in two places that we have lower than recommended contrast for our chosen font size. 

My first inclination is to bump up the font size, since both places (the header and the call to action buttons) can afford to be large.

**Comment by edthedev** [comment]
I'm using this to have a look at the contrast between our colors.
https://webaim.org/resources/contrastchecker/

**Comment by edthedev** [comment]
I did a 'right-click' then 'Inpsect Element' on the button that the WAVE tool flagged.
I grabbed both foreground and background color out of the Chrome 'Styles' tab, and put them into 
https://webaim.org/resources/contrastchecker/

I found that by adjusting the 'Lightness' slider on that page, I was able to get to passing scores at this value:

`#0D5C68`

**Comment by edthedev** [comment]
I'm taking detailed notes here in case I can't find a good tutorial to link to later and we want a how-to.

**Comment by edthedev** [comment]
'UIS Blue' from out existing stylesheet notes also passes, so I will switch that in.
#003366

**Comment by edthedev** [comment]
Darkening URL link foreground color to #004794 brings the test vs the gray background from failing to passing.

**Comment by MrMcFortna** [comment]
Have you seen the [Web Toolkit's Color Checker](https://builder.toolkit.illinois.edu/colorcheck/index.html) for testing combos of the official UIUC color scheme? It might be helpful in this situation.

**Comment by edthedev** [comment]
@MrMcFortna That tool is awesome! Thanks!

**Comment by MrMcFortna** [comment]
Glad it’s useful! H/T to its creator, Bryan Jonker!
