### ISSUE TITLE
Document SSO enabled ssh

### ISSUE THREAD

**Issue by trombonekenny** [uillinois-community/uillinois-community.github.io#6]
Point to the GitHub docs and/or share our learned knowledge about the steps needed (on the client and GitHub.com) to enable ssh keys on an SSO account.

**Comment by edthedev** [comment]
@trombonekenny  This looks like the correct resource:
https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-an-ssh-key-for-use-with-saml-single-sign-on

I'm going to add it to our pages.

Also, I thought I already made this comment, so I probably put a copy of this comment somewhere weird on this Friday afternoon.
